### ISSUE TITLE
Fruit Ninja Effect

### ISSUE THREAD

**Issue by artangco** [artrmz/VariousViewsEffects#10]
Hi,
I love the work you've done.  I'm looking for a Fruit Ninja chop in half effect which I'm hoping is a subset of the work you already do for the shatter effect.  Do you think that's easy to do by modifying one of the existing effects?

**Comment by artur-ios-dev** [comment]
Settings grid size to the (2,1) should be close to what you want. Unless you want to use gesture for that? Then it would need a little bit more editing.

**Comment by artangco** [comment]
I don't need gesture.  I'll try that thanks!
